apiVersion: cpd.ibm.com/v1
kind: Ibmcpd
metadata:
  name: ibmcpd-cr
  namespace: cpd
spec:
  license:
    accept: true
    license: "Enterprise"
  storageClass: "ocs-storagecluster-cephfs"
  version: "4.4.0"