apiVersion: ccs.cpd.ibm.com/v1beta1
kind: CCS
metadata:
  name: ccs-cr
  namespace: cpd
spec:
  license:
    accept: true
    license: "Enterprise"
  storageClass: "ocs-storagecluster-cephfs"
  version: "4.4.0"