apiVersion: cpd.ibm.com/v1
kind: Ibmcpd
metadata:
  name: ibmcpd-cr
  namespace: cp4d-instance
spec:
  license:
    accept: true
    license: "Enterprise"
  storageClass: "managed-nfs-storage"
  version: "4.4.0"