---
- name: Install and Configure PostgreSQL on RHEL9 for DataStage
  hosts: localhost
  become: yes # Requires root privileges

  vars:
    
  tasks:
    - name: 0. Reset stream and enable PostgreSQL 18
      ansible.builtin.shell: dnf module reset postgresql -y && dnf module enable postgresql:18 -y
      changed_when: false
      
    - name: 1. Install PostgreSQL 18 Server and Client (Forces upgrade)
      ansible.builtin.dnf:
        name: 
          - postgresql         # The client tool (pg_restore)
          - postgresql-server  # The database engine
        state: latest          # Forces override of the TechZone base image

    - name: 2. Initialize the PostgreSQL Database Cluster
      ansible.builtin.command: postgresql-setup --initdb
      args:
        creates: /var/lib/pgsql/data/postgresql.confly runs once

    - name: 3. Configure PostgreSQL to listen on all network interfaces
      ansible.builtin.lineinfile:
        path: /var/lib/pgsql/data/postgresql.conf
        regexp: "^#?listen_addresses"
        line: "listen_addresses = '*'"
        state: present
      notify: restart postgresql

    - name: 4. Allow Windows host to connect via pg_hba.conf
      ansible.builtin.lineinfile:
        path: /var/lib/pgsql/data/pg_hba.conf
        # It's good practice to use variables, but hardcoding your specific IP works too:
        line: "host    all             all             10.10.10.202/32         md5"
        insertafter: EOF
        state: present
      notify: restart postgresql

    - name: 4. Allow Windows host to connect via pg_hba.conf
      ansible.builtin.lineinfile:
        path: /var/lib/pgsql/data/pg_hba.conf
        line: "host    all             all             10.10.10.202/32         md5"
        insertafter: EOF
        state: present
      notify: restart postgresql

    - name: 4.1. Change default local authentication from ident to md5
      ansible.builtin.replace:
        path: /var/lib/pgsql/data/pg_hba.conf
        # This looks for the word 'ident' at the end of the line and swaps it to 'md5'
        regexp: 'ident$'
        replace: 'md5'
      notify: restart postgresql  

    - name: 5. Open RHEL 9 internal OS firewall for PostgreSQL
      ansible.builtin.shell: |
        firewall-cmd --add-service=postgresql --permanent
        firewall-cmd --reload
      ignore_errors: yes
      changed_when: false   

    - name: 6. Enable and Start PostgreSQL Service
      ansible.builtin.systemd:
        name: postgresql
        state: started
        enabled: yes

    - name: 6.1 Set password for the default postgres user
      ansible.builtin.shell: |
        psql -c "ALTER USER postgres WITH PASSWORD 'postgres';"
      become: yes
      become_user: postgres
      # This task is naturally idempotent; running it twice just overwrites the password with the same string.
    
    - name: 7. Check if target database already exists #Start Restore Phase
      ansible.builtin.shell: |
        psql -tAc "SELECT 1 FROM pg_database WHERE datname='demo';"
      become_user: postgres
      register: db_exists
      changed_when: false

    - name: 8. Create the empty target database
      ansible.builtin.command: createdb demo
      become_user: postgres
      when: db_exists.stdout != "1"

    - name: 9. Restore schemas and data from S3 dump
      ansible.builtin.command: >
        pg_restore -d demo -1 --no-owner --no-privileges /home/itzuser/electromart_demo.backup
      become_user: postgres
      when: db_exists.stdout != "1"

  handlers:
    - name: restart postgresql
      ansible.builtin.service:
        name: postgresql
        state: restarted