apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: deployer-ansible-pipeline
spec:
  workspaces:
    - name: pipeline-ws
  params:
    - name: ansiblePlaybook
      type: string
      description: "Injected by the operator from the JSON payload"
      default: "ibmtest/cp4d/deploy-cp4d-datastage.yml"
  tasks:
    - name: run-ansible
      taskSpec:
        workspaces:
          - name: source
        params:
          - name: playbookPath
            type: string
        steps:
          - name: execute-playbook
            image: quay.io/ansible/ansible-runner:latest
            workingDir: $(workspaces.source.path)
            env:
              - name: AWS_ACCESS_KEY_ID
                valueFrom:
                  secretKeyRef:
                    name: deployer-cp4d-secret
                    key: aws_access_key_id
              - name: AWS_SECRET_ACCESS_KEY
                valueFrom:
                  secretKeyRef:
                    name: deployer-cp4d-secret
                    key: aws_secret_access_key
            script: |
              #!/bin/sh
              echo "Starting TechZone V2 Ansible Deployment..."
              ansible-playbook $(params.playbookPath)
      params:
        - name: playbookPath
          value: $(params.ansiblePlaybook)
      workspaces:
        - name: source
          workspace: pipeline-ws