---
---
- id: 1
  name: "Jenkins_Devops"
  repository:
    url: "git@10.10.10.201:itzuser/electromart.git"
    branch: "main"
    assetPath: "datastage"
    testPath: "unittest"
    name: "electromart"
  compliance:
    url: "git@10.10.10.201:itzuser/compliance.git"
    branch: "main"
    includeRuleTags: []
    excludeRuleTags: []
    path: ""
    name: "compliance"
  issueManagementId: 0
